# Generated by Django 3.2 on 2022-01-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0007_remove_departamento_chefedepart'),
        ('Funcionarios', '0003_funcionario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='departamentos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamentos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento'),
            preserve_default=False,
        ),
    ]
