# Generated by Django 3.2 on 2022-01-18 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0005_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='documento',
            field=models.FileField(default=1, upload_to='documentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipoDoc',
            field=models.CharField(default=datetime.datetime(2022, 1, 18, 14, 3, 18, 402246, tzinfo=utc), help_text='Tipo de documento', max_length=30),
            preserve_default=False,
        ),
    ]
