# Generated by Django 3.2 on 2022-01-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0006_auto_20220118_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='tipoDoc',
        ),
    ]
