# Generated by Django 3.2 on 2022-01-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='name',
            new_name='nome',
        ),
    ]
