# Generated by Django 3.2 on 2022-01-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='chefeDepart',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
