# Generated by Django 3.2 on 2022-01-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_departamento_chefedepart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='empresa',
            new_name='empresas',
        ),
    ]
