# Generated by Django 3.2 on 2022-01-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0003_funcionario_email'),
        ('departamentos', '0004_rename_empresa_departamento_empresas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='chefeDepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Funcionarios.funcionario'),
        ),
    ]
