# Generated by Django 3.2 on 2022-01-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0003_funcionario_email'),
        ('departamentos', '0005_alter_departamento_chefedepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='chefeDepart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Funcionarios.funcionario'),
        ),
    ]
