# Generated by Django 3.2 on 2022-01-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_alter_departamento_chefedepart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='chefeDepart',
        ),
    ]
