# Generated by Django 3.2 on 2022-01-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Funcionarios', '0007_auto_20220120_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='documentos')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Funcionarios.funcionario')),
            ],
        ),
    ]
