# Generated by Django 3.2 on 2022-01-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='funcionario',
            new_name='pertence',
        ),
    ]
