# Generated by Django 3.2 on 2022-01-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0001_initial'),
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='funcionarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
